services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - database
    ports:
      - "5001:5001"
    environment:
      DB_HOST: database
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: pass
    networks:
      - backend_network
  
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3001:3001"

networks:
  backend_network:
    driver: bridge

volumes:
  db_data: